version: '3.7'

services:
  jobber:
    image: php
    ports:
      - 9502:${PORT}
    container_name: jobber
    network_mode: jobber
    env_file:
      - '.env'
    environment:
      DISABLE_DEFAULT_SERVER: 1
    volumes:
      - '.:/app'
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: php /app/index.php
